# Introduction to Python

## Assignment / Variables

In [23]:
x = 1
y = 9

When using Jupyter Notebooks, the order in which the cells are run is very important. 

In [25]:
x = 4
y = 2

In [26]:
# print the sum of the two variables x and y 
print(x+y)

6


In [15]:
print("Hello, Quantum Technology Enthusiasts!\n"*5)

Hello, Quantum Technology Enthusiasts!
Hello, Quantum Technology Enthusiasts!
Hello, Quantum Technology Enthusiasts!
Hello, Quantum Technology Enthusiasts!
Hello, Quantum Technology Enthusiasts!



In [18]:
print("Nice to "+"meet you!")

Nice to meet you!


## Lists in Python

In [27]:
int_list = [1,2,3,4]

print(int_list[0])

1


In [22]:
string_list = ["Today","is","a","good","day"]

print(string_list[len(string_list)-1])

day


In [24]:
any_list = [1,"Hi",9.0]

any_list[1]

'Hi'

## Conditional Statements

Indentation is very important in Python

In [28]:
if 3 == 3:
    print("3 is equal to 3")

3 is equal to 3


In [31]:
if 3 >= 3:
    print("3 is greater than or equal to 3")
else:
    print("3 is NOT greater than or equal to 3")

3 is greater than or equal to 3


In [30]:
if 3>=3 and 3<4:
    print("3 is greater than or equal to 3 AND 3 is less than 4")
else:
    print("3 is NOT greater than or equal to 3 OR 3 is NOT less than 4")

3 is greater than and equal to 3 and 3 is less than 4


In [32]:
weekdays = ["Monday","Tuesday","Wednesday","Thursday","Friday"]

if "Saturday" in weekdays:
    print("Saturday is a weekday")
else:
    print("Saturday is not a weekday")

Saturday is not a weekday


In [34]:
other_list = [4,"Yes",7.0]

if 4 in other_list:
    print("4 is in the other list")
else: 
    print("4 is not in the other list")

4 is in the other list


## Iteration

range() is a useful function when defining for loops

In [37]:
print(list(range(0,10)))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [38]:
print(list(range(0,10,2)))

[0, 2, 4, 6, 8]


In [39]:
print(list(range(1,10)))

[1, 2, 3, 4, 5, 6, 7, 8, 9]


In [40]:
print(list(range(10)))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


### For Loops

In [45]:
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9


### While Loops

In [44]:
i = 0

while i < 10:
    print(i)
    i += 1 

0
1
2
3
4
5
6
7
8
9


## Defining Methods

In [46]:
def doSomething():
    print("This method does something")

In [47]:
doSomething()

This method does something


In [70]:
def find_factors(num):
    factors = []
    for i in range(1,int(num/2)+1):
        if num%i == 0:
            factors.append(i)
    factors.append(num)
    return factors

In [71]:
find_factors(16)

[1, 2, 4, 8, 16]

In [72]:
find_factors(1)

[1]

### Exercise:
 using the find_factors method, write a method that will determine if a given number is a prime number

### Answer

In [73]:
def isPrimeNumber(num):
    factors_of_num = find_factors(num)
    if (1 in factors_of_num) and (num in factors_of_num):
        if len(factors_of_num) == 2:
            return True
        else:
            return False
    
    return False

In [79]:
isPrimeNumber(6)

False

## Numpy

In [2]:
import numpy as np

### Initialising an Array

In [3]:
zero_arr = np.zeros([5,1])

zero_arr

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [5]:
zero_arr = np.zeros([3,4])

zero_arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [7]:
# you can initialise an array with a list, this list will become the row of the array
arr_from_list = np.array([1,2,3,4])

arr_from_list 

array([1, 2, 3, 4])

In [10]:
# you can initialise an array with a list of lists, each list will be a new row of the array
arr_from_lists = np.array([[1,2,3],[4,5,6],[7,8,9]])

arr_from_lists

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Indexing an Array

In [11]:
arr_from_lists[0][1]

2

### Modifiying an array

In [12]:
arr_from_lists[0][1] = 100

arr_from_lists

array([[  1, 100,   3],
       [  4,   5,   6],
       [  7,   8,   9]])

#### Exercise:
write a function that iterates through an array and adds 10 to each number in the array

#### Answer:

In [16]:
def add_ten(arr):
    for i in range(arr.shape[0]):
        for j in range(arr.shape[1]):
            arr[i][j] = arr[i][j] + 10

    return arr

In [17]:
add_ten(arr_from_lists)

array([[ 12, 111,  14],
       [ 15,  16,  17],
       [ 18,  19,  20]])

In [18]:
# note: the original array is modified

arr_from_lists

array([[ 12, 111,  14],
       [ 15,  16,  17],
       [ 18,  19,  20]])

### Concatenating Arrays

In [3]:
arr_one = np.array([[1,2,3],[4,5,6]])

arr_two = np.array([[7,8,9],[10,11,12]])

# axis = 0 specifies that the rows are concatenated
np.concatenate((arr_one,arr_two),axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [4]:
# axis = 1 specifies that the columns are concatenated
np.concatenate((arr_one,arr_two),axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

### Other Important Functions with Numpy

#### Taking the Complex Conjugate of an Array

In [32]:
pauli_x = np.array([[0,1],[1,0]])
pauli_y = np.array([[0,-1j],[1j,0]])
pauli_z = np.array([[1,0],[0,-1]])

# finding the complex conjugate of an array
np.conj(pauli_x.T)

array([[0, 1],
       [1, 0]])

In [9]:
other_arr = np.array([[3j,4],[5j,6]])

# finding the complex conjugate of an array
np.conj(other_arr.T)

array([[0.-3.j, 0.-5.j],
       [4.-0.j, 6.-0.j]])

#### Matrix Multiplication

In [33]:
A = np.array([[1,2],[3,4]])
B = np.array([[1,0],[0,1]])

In [34]:
np.dot(A,B)

array([[1, 2],
       [3, 4]])

In [35]:
# this is a ROW vector, 1x2
v = np.array([1,0])

np.dot(v,A)

array([1, 2])

In [36]:
# this is a COLUMN vector, 2x1
v = np.array([[1],[0]])

np.dot(np.dot(A,B),v)

array([[1],
       [3]])